### ISSUE TITLE
 cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by cafe4it** [botbahlul/autosrt#5]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/autosrt/__init__.py", line 3329, in main
    wav_filepath, sample_rate = wav_converter(media_filepath)
    ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/bin/autosrt", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/autosrt/__init__.py", line 3548, in main
    if not KeyboardInterrupt in str(e):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'in <string>' requires string as left operand, not type

**Comment by botbahlul** [comment]
1. are you using compiled executable from release page or install this app with pip?
2. what command did you type exactly? please give me a complete screenshot (command you typed and all outputs)
